// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace HydrationApp
{
    [Microsoft.UI.Xaml.Data.Bindable]
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainWindow();
        String HydrationOutputText;
        String CancellationOutputText;
    }
}
